spring.application.name=backend
spring.config.import=optional:application.properties.secrets
spring.datasource.url=${db.url}
spring.datasource.username=${db.user}
spring.datasource.password=${db.password}
